=== dtag-dbu/psikeds/KnowledgeBaseEditor/src/psiKedsXtxKrl/psikeds.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
psiKeds :- ps induced knowledge entity delivery system

Copyright (c) 2013, 2014 Karsten Reincke, Marco Juliano, Deutsche Telekom AG

This file is free software: you can redistribute
it and/or modify it under the terms of the
[X] GNU Affero General Public License
[ ] GNU General Public License
[ ] GNU Lesser General Public License
[ ] Creatice Commons ShareAlike 3.0 License

For details see file LICENSING in the top project directory
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://org.psikeds.knowledgebase"
  xmlns:kb="http://org.psikeds.knowledgebase">

  <xs:element name="knowledgebase">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="kb:meta" />
        <xs:element ref="kb:data"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="meta">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="kb:id"/>
        <xs:element ref="kb:name" minOccurs="0" />
        <xs:element ref="kb:teaser" minOccurs="0" />
        <xs:element ref="kb:release" minOccurs="0"  />
        <xs:element ref="kb:copyright" minOccurs="0" />
        <xs:element ref="kb:license" minOccurs="0" />
        <xs:element ref="kb:created" minOccurs="0" />
        <xs:element ref="kb:lastmodified" minOccurs="0" />
        <xs:element ref="kb:language" minOccurs="0" />
        <xs:element ref="kb:creator" minOccurs="0"  maxOccurs="unbounded" />
        <xs:element ref="kb:description" minOccurs="0"  maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="id" type="kb:nonEmptyString"/>
  <xs:element name="name" type="kb:nonEmptyString"/>
  <xs:element name="teaser" type="kb:nonEmptyString"/>
  <xs:element name="release" type="kb:nonEmptyString"/>
  <xs:element name="copyright" type="kb:nonEmptyString"/>
  <xs:element name="license" type="kb:nonEmptyString"/>
  <xs:element name="created" type="kb:nonEmptyString"/>
  <xs:element name="lastmodified" type="kb:nonEmptyString"/>
  <xs:element name="language" type="kb:nonEmptyString"/>
  <xs:element name="creator" type="kb:nonEmptyString"/>

  <xs:element name="data">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="kb:sensors" minOccurs="0"/>
        <xs:element ref="kb:concepts" minOccurs="0"/>
        <xs:element ref="kb:purposes"/>
        <xs:element ref="kb:variants"/>
        <xs:element ref="kb:alternatives"/>
        <xs:element ref="kb:constituents" minOccurs="0"/>
        <xs:element ref="kb:derivations" minOccurs="0"/>
        <xs:element ref="kb:events" minOccurs="0"/>
        <xs:element ref="kb:parameters" minOccurs="0"/>
        <xs:element ref="kb:rules" minOccurs="0"/>
        <xs:element ref="kb:relations" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="sensors">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="kb:sensor" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="sensor">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="kb:label"/>
        <xs:element ref="kb:description" minOccurs="0"/>
        <xs:element ref="kb:unit"  minOccurs="0" />
        <xs:element ref="kb:values"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:ID"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="unit" type="kb:nonEmptyString"/>

  <xs:element name="values">
    <xs:complexType>
      <xs:sequence>
        <xs:choice>
          <xs:element ref="kb:strValue" minOccurs="1" maxOccurs="unbounded" />
          <xs:choice minOccurs="1" maxOccurs="unbounded">
            <xs:element ref="kb:intValue" />
            <xs:element ref="kb:intRange" />
          </xs:choice>
          <xs:choice minOccurs="1" maxOccurs="unbounded">
            <xs:element ref="kb:floatValue" />
            <xs:element ref="kb:floatRange" />
          </xs:choice>            
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="strValue" type="kb:sensedStringValue" />

  <xs:complexType name="sensedStringValue"> 
    <xs:simpleContent>
      <xs:extension base="xs:string"> 
        <xs:attribute name="id" use="required" type="xs:ID"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:element name="intValue" type="kb:sensedIntValue" />

  <xs:complexType name="sensedIntValue"> 
    <xs:simpleContent>
      <xs:extension base="xs:integer"> 
        <xs:attribute name="id" use="required" type="xs:ID"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

   <xs:element name="intRange">
    <xs:complexType>
      <xs:attribute name="id" use="required" type="xs:ID"/>
      <xs:attribute name="min" type="xs:integer"/> 
      <xs:attribute name="max" type="xs:integer"/>          
      <xs:attribute name="inc" type="xs:integer" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="floatValue" type="kb:sensedFloatValue" />

  <xs:complexType name="sensedFloatValue"> 
    <xs:simpleContent>
      <xs:extension base="xs:float"> 
        <xs:attribute name="id" use="required" type="xs:ID"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

   <xs:element name="floatRange">
    <xs:complexType>
      <xs:attribute name="id" use="required" type="xs:ID"/>
      <xs:attribute name="min" type="xs:float"/> 
      <xs:attribute name="max" type="xs:float"/>          
      <xs:attribute name="inc" type="xs:float" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="concepts">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="kb:concept"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="concept">
    <xs:complexType>
      <xs:sequence >
        <xs:element ref="kb:label" />
        <xs:element ref="kb:description" minOccurs="0" />
        <xs:element ref="kb:attributes" />
      </xs:sequence>
      <xs:attribute name="conceptRef" type="xs:IDREF"/>
      <xs:attribute name="id" type="xs:ID"/> 
    </xs:complexType>
  </xs:element>

  <xs:element name="attributes">
    <xs:complexType>
      <xs:sequence>
        <xs:element  ref="kb:attribute" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="purposes">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="kb:purpose"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="purpose">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="kb:label"/>
        <xs:element ref="kb:description" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:ID"/>
      <xs:attribute name="root" use="optional" type="xs:boolean" />
    </xs:complexType>
  </xs:element>

  <xs:element name="variants">
    <xs:complexType>
      <xs:sequence>
        <xs:element  ref="kb:variant" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="variant">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="kb:label"/>
        <xs:element ref="kb:description" minOccurs="0" />
        <xs:element ref="kb:primarilyDenotedBy" minOccurs="0" />
        <xs:element ref="kb:secondarilyDenotedBy" minOccurs="0" />
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:ID"/>
      <xs:attribute name="singleton" use="optional" type="xs:boolean" />
      <xs:attribute name="type" use="required" type="kb:VarType"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="primarilyDenotedBy">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="kb:oneOutOfTheseStrAttributes"  minOccurs="0"/>
        <xs:element ref="kb:oneOutOfTheseIntAttributes" minOccurs="0" />      
        <xs:element ref="kb:oneOutOfTheseFloatAttributes" minOccurs="0" />
        <xs:element ref="kb:oneOutOfThisRange" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="kb:oneOutOfTheseTerminalConcepts" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="oneOutOfTheseStrAttributes">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="kb:attribute" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="oneOutOfTheseFloatAttributes">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="kb:attribute"  minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="oneOutOfTheseIntAttributes">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="kb:attribute"  minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="oneOutOfThisRange">
    <xs:complexType>
      <xs:attribute name="rangeRef" use="required" type="xs:IDREF"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="oneOutOfTheseTerminalConcepts">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="kb:subsumption" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="secondarilyDenotedBy">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="kb:subsumption" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

    <xs:element name="subsumption">
    <xs:complexType>
      <xs:attribute name="ref" type="xs:IDREF"/>
      <xs:attribute name="type" type="kb:ConceptType"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="alternatives">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="kb:fulfills"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="fulfills">
    <xs:complexType>
      <xs:attribute name="psRef" use="required" type="xs:IDREF"/>
      <xs:attribute name="pvRefs" use="required" type="xs:IDREFS"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="constituents">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="kb:constitutes" minOccurs="1"  maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="constitutes">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="kb:component" minOccurs="1"  maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="pvRef" use="required" type="xs:IDREF"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="component">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="kb:quantity" minOccurs="0"  maxOccurs="1" />
      </xs:sequence>
      <xs:attribute name="psRef" use="required" type="xs:IDREF"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="derivations">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="kb:setup" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="setup">
    <xs:complexType>
      <xs:attribute name="pvImplRef" use="required" type="xs:IDREF"/>
      <xs:attribute name="psRefs" use="required" type="xs:IDREFS"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="events">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="kb:event"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="event">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="kb:label"/>
        <xs:element ref="kb:description" minOccurs="0" />
        <xs:element ref="kb:trigger"/>
      </xs:sequence>

      <xs:attribute name="id" use="required" type="xs:ID"/>
      <xs:attribute name="nexusRef" use="required" type="xs:IDREF"/>
      <xs:attribute name="contextPath" use="required" type="xs:IDREFS"/>     
    </xs:complexType>
  </xs:element>

  <xs:element name="trigger">
    <xs:complexType>
      <xs:attribute name="ref" use="required" type="xs:IDREF"/>
      <xs:attribute name="type" use="required" type="kb:TriggerType"/>
      <xs:attribute name="notEvent" use="optional" type="xs:boolean" />
    </xs:complexType>
  </xs:element>

  <xs:element name="parameters">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="kb:parameter" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="parameter">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="kb:label"/>
        <xs:element ref="kb:description" minOccurs="0" />
        <xs:element ref="kb:valueSet"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:ID"/>
      <xs:attribute name="nexusRef" use="required" type="xs:IDREF"/>
      <xs:attribute name="contextPath" use="required" type="xs:IDREFS"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="valueSet">
    <xs:complexType>
      <xs:attribute name="sensorRef" use="required" type="xs:IDREF"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="rules">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="kb:rule" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="rule">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="kb:label"/>
        <xs:element ref="kb:description" minOccurs="0" />
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:ID"/>
      <xs:attribute name="nexusRef" use="required" type="xs:IDREF"/>  
      <xs:attribute name="premiseRefs" use="required" type="xs:IDREFS" />                
      <xs:attribute name="conclusioRef" use="required" type="xs:IDREF"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="relations">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="kb:relation" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="relation">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="kb:label"/>
        <xs:element ref="kb:description" minOccurs="0" />
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:ID"/>
      <xs:attribute name="nexusRef" use="required" type="xs:IDREF"/>           
      <xs:attribute name="condRef" use="optional" type="xs:IDREF"/>
      <xs:attribute name="lpRef" use="required" type="xs:IDREF"/>
      <xs:attribute name="lpType" use="required" type="kb:RelParamType"/>
      <xs:attribute name="relType" use="required" type="kb:RelationType"/>
      <xs:attribute name="rpRef" use="required" type="xs:IDREF"/>
      <xs:attribute name="rpType" use="required" type="kb:RelParamType"/>
    </xs:complexType>
  </xs:element>

  <!-- ============================================================== -->
  <!-- Basic attributes, types and restrictions -->
  <!-- ============================================================== -->

 <!-- used to denote sensored values in concepts and variant valuelists -->
   <xs:element name="attribute">
    <xs:complexType>
      <xs:attribute name="type" use="required" type="kb:SpecificAttributeType"/>
      <xs:attribute name="ref" use="required" type="xs:IDREF"/>
    </xs:complexType>
  </xs:element>  
 
 <!-- used in nearly all defined knowledge base tokens -->
 
  <xs:element name="label" type="kb:nonEmptyString" />
  <xs:element name="description" type="xs:string" />

  <xs:simpleType name="RelationType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="eq"/>
      <xs:enumeration value="neq"/>
      <xs:enumeration value="less"/>
      <xs:enumeration value="leq"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="RelParamType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="vVal"/>
      <xs:enumeration value="cInt"/>
      <xs:enumeration value="cFloat"/>
      <xs:enumeration value="cStr"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="SpecificAttributeType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="str"/>
      <xs:enumeration value="int"/>
      <xs:enumeration value="float"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TriggerType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="pv"/>
      <xs:enumeration value="attribute"/>
      <xs:enumeration value="concept"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="VarType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="explicit"/>
      <xs:enumeration value="implicit"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="ConceptType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="sensored"/>
      <xs:enumeration value="derived"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="nonEmptyString">
    <xs:restriction base="xs:string">
      <xs:minLength value="1" />
      <xs:pattern value="[^\t\n\r\s]*.*[^\t\n\r\s]*" />
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="quantity" type="kb:positiveNumber" />

  <xs:simpleType name="positiveNumber">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0" />
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== dtag-dbu/psikeds/config/ldrewe.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
ldrewe : 0.90 : demo database for the lecture on Linux Days 2014/Berlin 
(C) Karsten Reincke, Deutsche Telekom AG, Darmstadt 2014 

A psiKeds knowledge base: developed for being used by the inference machine
of psiKeds, the purpose system induced knowledge entity delivery system
http://www.psikeds.org/) and generated by the psiKedsXtXKrl-Generator

This file is licensed under the conditions of a/the
CC-BY-SA-4.0

-->
<kb:knowledgebase 
  xmlns="http://org.psikeds.knowledgebase"
  xmlns:kb="http://org.psikeds.knowledgebase"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://org.psikeds.knowledgebase psikeds.xsd">
  <kb:meta>
    <kb:id>ldrewe</kb:id>
    <kb:name>Linux-Day-Rewe-Demo-Knowledgebase</kb:name>
    <kb:teaser>Linux-Day-Rewe-Demo-Knowledgebase</kb:teaser>
    <kb:release>0.90</kb:release>
    <kb:copyright>Karsten Reincke, Deutsche Telekom AG, Darmstadt 2014</kb:copyright>
    <kb:license>CC-BY-SA-4.0</kb:license>
    <kb:created>2014-05-05</kb:created>
    <kb:lastmodified>2014-05-05</kb:lastmodified>
    <kb:creator>Karsten Reincke</kb:creator>
  </kb:meta>
  <kb:data>

      
    <kb:purposes>
      <kb:purpose id="relishDinner" root="true">
        <kb:label>relish.Dinner</kb:label>
      </kb:purpose>
      <kb:purpose id="addTaste" root="false">
        <kb:label>add:Taste</kb:label>
      </kb:purpose>
      <kb:purpose id="addVitamins" root="false">
        <kb:label>add:Vitamins</kb:label>
      </kb:purpose>
      <kb:purpose id="addProteins" root="false">
        <kb:label>add:Proteins</kb:label>
      </kb:purpose>
      <kb:purpose id="addCarbohydrats" root="false">
        <kb:label>add:Carbohydrats</kb:label>
      </kb:purpose>
    </kb:purposes>

    <kb:variants>
      <kb:variant id="VeggiMeal"
        type="explicit">
        <kb:label>Veggi Meal</kb:label>
      </kb:variant>
      
      <kb:variant id="CarniMeal"
        type="explicit">
        <kb:label>Carni Meal</kb:label>
      </kb:variant>
      
      <kb:variant id="Hollandaise"
        type="explicit">
        <kb:label>Sauce Hollandaise</kb:label>
      </kb:variant>
      
      <kb:variant id="BratenSosse"
        type="explicit">
        <kb:label>Bratenso√üe</kb:label>
      </kb:variant>
      
      <kb:variant id="Spargel"
        type="explicit">
        <kb:label>Spargel</kb:label>
      </kb:variant>
      
      <kb:variant id="Erbsen"
        type="explicit">
        <kb:label>Erbsen</kb:label>
      </kb:variant>
      
      <kb:variant id="Schinken"
        type="explicit">
        <kb:label>Schinken</kb:label>
      </kb:variant>
      
      <kb:variant id="Braten"
        type="explicit">
        <kb:label>Braten</kb:label>
      </kb:variant>
      
      <kb:variant id="Kartoffeln"
        type="explicit">
        <kb:label>Kartoffeln</kb:label>
      </kb:variant>
      
      <kb:variant id="Nudeln"
        type="explicit">
        <kb:label>Nudeln</kb:label>
      </kb:variant>
      
    </kb:variants>  

    <kb:alternatives>
      <kb:fulfills psRef="relishDinner"
        pvRefs="VeggiMeal CarniMeal " />
      <kb:fulfills psRef="addTaste"
        pvRefs="Hollandaise BratenSosse " />
      <kb:fulfills psRef="addVitamins"
        pvRefs="Spargel Erbsen " />
      <kb:fulfills psRef="addProteins"
        pvRefs="Braten Schinken " />
      <kb:fulfills psRef="addCarbohydrats"
        pvRefs="Kartoffeln Nudeln " />
    </kb:alternatives>  
     
    <kb:constituents>
      <kb:constitutes pvRef="VeggiMeal">
        <kb:component psRef="addTaste">
          <kb:quantity>1</kb:quantity>
        </kb:component>
        <kb:component psRef="addVitamins">
          <kb:quantity>1</kb:quantity>
        </kb:component>
        <kb:component psRef="addCarbohydrats">
          <kb:quantity>1</kb:quantity>
        </kb:component>
      </kb:constitutes>  
      <kb:constitutes pvRef="CarniMeal">
        <kb:component psRef="addTaste">
          <kb:quantity>1</kb:quantity>
        </kb:component>
        <kb:component psRef="addVitamins">
          <kb:quantity>1</kb:quantity>
        </kb:component>
        <kb:component psRef="addProteins">
          <kb:quantity>1</kb:quantity>
        </kb:component>
        <kb:component psRef="addCarbohydrats">
          <kb:quantity>1</kb:quantity>
        </kb:component>
      </kb:constitutes>  
    </kb:constituents> 

    
    <kb:events>
      <kb:event id="VeggiMealWithHollandaise" 
        nexusRef="VeggiMeal"
        contextPath="VeggiMeal addTaste"> 
        <kb:label>Veggi Meal mit Hollandaise</kb:label>
          <kb:trigger  type="pv" ref="Hollandaise" />
       </kb:event>
      <kb:event id="VeggiMealWithSpargel" 
        nexusRef="VeggiMeal"
        contextPath="VeggiMeal addVitamins"> 
        <kb:label>Veggi Meal mit Spargel</kb:label>
          <kb:trigger  type="pv" ref="Spargel" />
       </kb:event>
      <kb:event id="CarniMealWithHollandaise" 
        nexusRef="CarniMeal"
        contextPath="CarniMeal addTaste"> 
        <kb:label>Carni Meal mit Hollandaise</kb:label>
          <kb:trigger  type="pv" ref="Hollandaise" />
       </kb:event>
      <kb:event id="CarniMealWithSpargel" 
        nexusRef="CarniMeal"
        contextPath="CarniMeal addVitamins"> 
        <kb:label>Carni Meal mit Spargel</kb:label>
          <kb:trigger  type="pv" ref="Spargel" />
       </kb:event>
      <kb:event id="CarniMealWithSchinken" 
        nexusRef="CarniMeal"
        contextPath="CarniMeal addProteins"> 
        <kb:label>Carni Meal mit Schinken</kb:label>
          <kb:trigger  type="pv" ref="Schinken" />
       </kb:event>
      <kb:event id="CarniMealWithKartoffeln" 
        nexusRef="CarniMeal"
        contextPath="CarniMeal addCarbohydrats"> 
        <kb:label>Carni Meal mit Kartoffeln</kb:label>
          <kb:trigger  type="pv" ref="Kartoffeln" />
       </kb:event>
      <kb:event id="VeggiMealWithKartoffeln" 
        nexusRef="VeggiMeal"
        contextPath="VeggiMeal addCarbohydrats"> 
        <kb:label>VeggiMeal mit Kartoffeln</kb:label>
          <kb:trigger  type="pv" ref="Kartoffeln" />
       </kb:event>
    </kb:events> 
    
    
    <kb:rules>
      <kb:rule id="IFVMwithHoolandaiseTHENVMwithSpargel"
        nexusRef="VeggiMeal"
        premiseRefs="VeggiMealWithHollandaise "
        conclusioRef="VeggiMealWithSpargel" >
        <kb:label>IF VM mit Hoolandaise THEN VM mit Spargel</kb:label>
      </kb:rule>
      <kb:rule id="IFVMwithSpargelTHENVMwithHoolandaise"
        nexusRef="VeggiMeal"
        premiseRefs="VeggiMealWithSpargel "
        conclusioRef="VeggiMealWithHollandaise" >
        <kb:label>IF VM mit Spargel THEN VM mit Hollandaise</kb:label>
      </kb:rule>
      <kb:rule id="IFCMwithHoolandaiseTHENCMwithSpargel"
        nexusRef="CarniMeal"
        premiseRefs="CarniMealWithHollandaise "
        conclusioRef="CarniMealWithSpargel" >
        <kb:label>IF CM mit Hoolandaise THEN CM mit Spargel</kb:label>
      </kb:rule>
      <kb:rule id="IFCMwithSpargelTHENCMwithHoolandaise"
        nexusRef="CarniMeal"
        premiseRefs="CarniMealWithSpargel "
        conclusioRef="CarniMealWithHollandaise" >
        <kb:label>IF CM mit Spargel THEN CM mit Hollandaise</kb:label>
      </kb:rule>
      <kb:rule id="IFCMwithSpargelTHENCMwithSchinken"
        nexusRef="CarniMeal"
        premiseRefs="CarniMealWithSpargel "
        conclusioRef="CarniMealWithSchinken" >
        <kb:label>IF CM mit Spargel THEN CM mit Schinken</kb:label>
      </kb:rule>
      <kb:rule id="IFCMwithSpargelTHENCMwithKartoffeln"
        nexusRef="CarniMeal"
        premiseRefs="CarniMealWithSpargel "
        conclusioRef="CarniMealWithKartoffeln" >
        <kb:label>IF CM mit Spargel THEN CM mit Kartoffeln</kb:label>
      </kb:rule>
      <kb:rule id="IFVMwithSpargelTHENVMwithKartoffeln"
        nexusRef="VeggiMeal"
        premiseRefs="VeggiMealWithSpargel "
        conclusioRef="VeggiMealWithKartoffeln" >
        <kb:label>IF VM mit Spargel THEN VM mit Kartoffeln</kb:label>
      </kb:rule>
    </kb:rules> 
    
  </kb:data>    
</kb:knowledgebase>
