=== dtag-dbu/psikeds/KnowledgeBase/src/main/resources/kb.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="http://org.psikeds.knowledgebase"
    targetNamespace="http://org.psikeds.knowledgebase">

    <!-- This XSD describes the syntax of a psiKeds Knowledge Base.
    
         Note:
         1. All elements are defined on top-level and then referenced
            by other elements (Salami Slice Design).
         2. Element-Types are identical to Element-Names.

         ==> Both might not be best practices from an XSD point of
             view, but it results in JAXB-Classes that are very nice
             for the StAX-Parser. ;-)
     -->

    <!-- ============================================================== -->
    <!--      XML-Root-Element, entry point of our knowledge base       -->
    <!-- ============================================================== -->

    <xs:element name="knowledgebase" type="knowledgebase" />

    <xs:complexType name="knowledgebase">
        <xs:sequence>
            <xs:element ref="meta" minOccurs="0" maxOccurs="1" />
            <xs:element ref="data" />
        </xs:sequence>
    </xs:complexType>

    <!-- ============================================================== -->
    <!--      Sub-Elements, defined in global scope                     -->
    <!-- ============================================================== -->

    <xs:element name="meta" type="meta" />

    <xs:complexType name="meta">
        <xs:sequence>
            <xs:element ref="created" minOccurs="0" maxOccurs="1" />
            <xs:element ref="lastmodified" minOccurs="0" maxOccurs="1" />
            <xs:element ref="creator" minOccurs="0" maxOccurs="unbounded" />
            <xs:element ref="description" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <!-- ============================================================== -->

    <xs:element name="data" type="data" />

    <xs:complexType name="data">
        <xs:sequence>
            <xs:element ref="features" minOccurs="0" maxOccurs="1" />       <!-- features/atributes of purposes and variants -->
            <xs:element ref="purposes" />                                   <!-- ps nodes -->
            <xs:element ref="variants" />                                   <!-- pv nodes -->
            <xs:element ref="alternatives" minOccurs="0" maxOccurs="1" />   <!-- is-a releations, i.e. edges from pv to ps -->
            <xs:element ref="constituents" minOccurs="0" maxOccurs="1" />   <!-- has-a releatons, i.e. edges from ps to pv -->
            <xs:element ref="events" minOccurs="0" maxOccurs="1" />         <!-- event e = path pv->ps->pv->ps->... -->
            <xs:element ref="rules" minOccurs="0" maxOccurs="1" />          <!-- if e1+e2+e3 => evt -->
        </xs:sequence>
    </xs:complexType>

    <!-- ============================================================== -->

    <xs:element name="features" type="features" />

    <xs:complexType name="features">
        <xs:sequence>
            <xs:element ref="feature" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:element name="feature" type="feature" />

    <xs:complexType name="feature">
        <xs:sequence>
            <xs:element ref="label" />
            <xs:element ref="description" minOccurs="0" maxOccurs="1" />
            <!-- TODO -->
        </xs:sequence>
        <xs:attribute ref="id" use="required"/>
    </xs:complexType>

    <!-- ============================================================== -->

    <xs:element name="purposes" type="purposes" />

    <xs:complexType name="purposes">
        <xs:sequence>
            <xs:element ref="purpose" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:element name="purpose" type="purpose" />

    <xs:complexType name="purpose">
        <xs:sequence>
            <xs:element ref="label" />
            <xs:element ref="description" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
        <xs:attribute ref="id" use="required"/>
    </xs:complexType>

    <!-- ============================================================== -->

    <xs:element name="variants" type="variants" />

    <xs:complexType name="variants">
        <xs:sequence>
            <xs:element ref="variant" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:element name="variant" type="variant" />

    <xs:complexType name="variant">
        <xs:sequence>
            <xs:element ref="label" />
            <xs:element ref="description" minOccurs="0" maxOccurs="1" />
            <!-- TODO -->
        </xs:sequence>
        <xs:attribute ref="id" use="required"/>
    </xs:complexType>

    <!-- ============================================================== -->

    <xs:element name="alternatives" type="alternatives" />

    <xs:complexType name="alternatives">
        <xs:sequence>
            <xs:element ref="fulfills" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:element name="fulfills" type="fulfills" />

    <xs:complexType name="fulfills">
        <xs:sequence>
            <xs:element ref="purpose" />    <!-- a pupose is fulfilled by one or several variant(s) -->
            <xs:choice>
              <xs:element ref="variant" />
              <xs:element ref="variants" />
            </xs:choice>
            <xs:element ref="description" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
    </xs:complexType>

    <!-- ============================================================== -->

    <xs:element name="constituents" type="constituents" />

    <xs:complexType name="constituents">
        <xs:sequence>
            <xs:element ref="constitutes" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:element name="constitutes" type="constitutes" />

    <xs:complexType name="constitutes">
        <xs:sequence>
            <xs:element ref="variant" />    <!-- a variant is constituted by one or several purposes(s) -->
            <xs:choice>
              <xs:element ref="purpose" />
              <xs:element ref="purposes" />
            </xs:choice>
            <xs:element ref="description" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
    </xs:complexType>

    <!-- ============================================================== -->

    <xs:element name="events" type="events" />

    <xs:complexType name="events">
        <xs:sequence>
            <xs:element ref="event" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:element name="event" type="event" />

    <xs:complexType name="event">
        <xs:sequence>
            <xs:element ref="path" />
            <xs:element ref="purpose" />
            <xs:element ref="description" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
        <xs:attribute ref="id" use="required"/>
    </xs:complexType>

    <xs:element name="path" type="path" />

    <xs:complexType name="path">
        <xs:sequence>
            <xs:element ref="variant" />
            <xs:element ref="purpose" />
            <!-- TODO -->
        </xs:sequence>
    </xs:complexType>

    <!-- ============================================================== -->

    <xs:element name="rules" type="rules" />

    <xs:complexType name="rules">
        <xs:sequence>
            <xs:element ref="rule" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:element name="rule" type="rule" />

    <xs:complexType name="rule">
        <xs:sequence>
            <xs:element ref="label" />
            <xs:element ref="description" minOccurs="0" maxOccurs="1" />
            <!-- TODO -->
        </xs:sequence>
        <xs:attribute ref="id" use="required"/>
    </xs:complexType>

    <!-- ============================================================== -->
    <!--      Basic attributes, types and restrictions                  -->
    <!-- ============================================================== -->

    <xs:attribute name="id" type="id" />

    <xs:simpleType name="id">
        <xs:restriction base="xs:string">
             <xs:minLength value="1" />
             <xs:maxLength value="20" />
             <xs:pattern value="([a-zA-Z0-9])+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="created" type="xs:dateTime" />

    <xs:element name="lastmodified" type="xs:dateTime" />

    <xs:element name="creator" type="nonEmptyString" />

    <xs:element name="label" type="nonEmptyString" />

    <xs:element name="description" type="nonEmptyString" />

    <xs:simpleType name="nonEmptyString">
        <xs:restriction base="xs:string">
             <xs:minLength value="1" />
             <xs:maxLength value="255" />
        </xs:restriction>
    </xs:simpleType>
	
</xs:schema>

=== dtag-dbu/psikeds/KnowledgeBase/src/main/resources/expired/kb20140210.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
psiKeds :- ps induced knowledge entity delivery system

Copyright (c) 2013, 2014 Karsten Reincke, Marco Juliano, Deutsche Telekom AG

This file is free software: you can redistribute
it and/or modify it under the terms of the
[ ] GNU Affero General Public License
[ ] GNU General Public License
[ ] GNU Lesser General Public License
[X] Creatice Commons ShareAlike 3.0 License

For details see file LICENSING in the top project directory
-->
<kb:knowledgebase xmlns="http://org.psikeds.knowledgebase"
  xmlns:kb="http://org.psikeds.knowledgebase"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://org.psikeds.knowledgebase kb.xsd">

  <kb:meta>
    <kb:created>2013-09-09T12:00:00</kb:created>
    <kb:lastmodified>2013-12-03T19:37:23</kb:lastmodified>
    <kb:creator>marco@juliano.de</kb:creator>
    <kb:description>A simple example of a Knowledge Base</kb:description>
    <kb:description>Status: Work in Progress</kb:description>
  </kb:meta>

  <kb:data>

    <kb:features>
      <kb:feature id="f0001">
        <kb:label>A decimal number</kb:label>
        <kb:value>42.0</kb:value>
        <kb:featureValueType>float</kb:featureValueType>
      </kb:feature>
      <kb:feature id="f0002">
        <kb:label>A Range from 1 to 10</kb:label>
        <kb:range>
          <kb:minValue>1</kb:minValue>
          <kb:maxValue>10</kb:maxValue>
        </kb:range>
        <kb:featureValueType>integer</kb:featureValueType>
      </kb:feature>
      <kb:feature id="f0003">
        <kb:label>Just a String</kb:label>
        <kb:value>String Text Characters Letters Whatever</kb:value>
        <kb:featureValueType>string</kb:featureValueType>
      </kb:feature>
      <kb:feature id="f0004">
        <kb:label>This is a boolean Value</kb:label>
        <kb:value>true</kb:value>
        <kb:featureValueType>boolean</kb:featureValueType>
      </kb:feature>
    </kb:features>

    <kb:purposes>
      <kb:purpose id="p1" root="true">
        <kb:label>Sweets</kb:label>
      </kb:purpose>
      <kb:purpose id="p2" root="true">
        <kb:label>Packaging</kb:label>
      </kb:purpose>
      <kb:purpose id="p3" root="true">
        <kb:label>Drinking</kb:label>
      </kb:purpose>
      <kb:purpose id="p111">
        <kb:label>Be Milky</kb:label>
      </kb:purpose>
      <kb:purpose id="p112">
        <kb:label>Have Chocolate</kb:label>
      </kb:purpose>
    </kb:purposes>

    <kb:variants>
      <kb:variant id="v11" hasFeatures="f0002 f0003">
        <kb:label>Milk Chocolate</kb:label>
      </kb:variant>
      <kb:variant id="v12" hasFeatures="f0001 f0002">
        <kb:label>Diet Chocolate</kb:label>
      </kb:variant>
      <kb:variant id="v1111" hasFeatures="f0003 f0004">
        <kb:label>Soya Milk</kb:label>
      </kb:variant>
      <kb:variant id="v1112" hasFeatures="f0004">
        <kb:label>Low Fat Milk</kb:label>
      </kb:variant>
      <kb:variant id="v1113">
        <kb:label>Full Flavoured Milk</kb:label>
      </kb:variant>
      <kb:variant id="v1121" hasFeatures="f0003 f0004">
        <kb:label>Dark Chocolate</kb:label>
      </kb:variant>
      <kb:variant id="v1122" hasFeatures="f0003">
        <kb:label>50% Chocolate</kb:label>
      </kb:variant>
      <kb:variant id="v1123">
        <kb:label>White Chocolate</kb:label>
      </kb:variant>
      <kb:variant id="v13">
        <kb:label>Gummy Bears</kb:label>
      </kb:variant>
      <kb:variant id="v14">
        <kb:label>Twix</kb:label>
      </kb:variant>
      <kb:variant id="v15">
        <kb:label>Duplo</kb:label>
      </kb:variant>
      <kb:variant id="v16">
        <kb:label>Licorice</kb:label>
      </kb:variant>
      <kb:variant id="v21">
        <kb:label>No Packaging</kb:label>
      </kb:variant>
      <kb:variant id="v22">
        <kb:label>Cardboard Box</kb:label>
      </kb:variant>
      <kb:variant id="v23">
        <kb:label>Aluminum Foil</kb:label>
      </kb:variant>
      <kb:variant id="v24">
        <kb:label>Bottle</kb:label>
      </kb:variant>
      <kb:variant id="v25">
        <kb:label>Can</kb:label>
      </kb:variant>
      <kb:variant id="v31">
        <kb:label>Coca Cola</kb:label>
      </kb:variant>
      <kb:variant id="v32">
        <kb:label>Pepsi Cola</kb:label>
      </kb:variant>
      <kb:variant id="v33">
        <kb:label>Budweiser</kb:label>
      </kb:variant>
      <kb:variant id="v34">
        <kb:label>Mineral Water</kb:label>
      </kb:variant>
      <kb:variant id="v35">
        <kb:label>Red Wine</kb:label>
      </kb:variant>
    </kb:variants>

    <kb:alternatives>
      <!-- purpose p1 is fulfilled by variant v11 or v12 or v13 or ... -->
      <kb:fulfills purposeID="p1" variantID="v11 v12 v13 v14 v15 v16" />
      <kb:fulfills purposeID="p111" variantID="v1111 v1112 v1113">
        <kb:quantity>2</kb:quantity>
        <kb:description>Purpose p111 is fulfilled by 2 entities of variants v1111, v1112 or v1113</kb:description>
      </kb:fulfills>
      <kb:fulfills purposeID="p112" variantID="v1121 v1122 v1123">
        <kb:quantity>1</kb:quantity>
        <kb:description>Purpose p112 is fulfilled by variant v1121, v1122 or v1123</kb:description>
      </kb:fulfills>
      <!-- purpose p2 is fulfilled by variant v21 or v22 or ... -->
      <kb:fulfills purposeID="p2" variantID="v21 v22 v23 v24 v25" />
      <!-- purpose p3 is fulfilled by variant v31 or v32 or ... -->
      <kb:fulfills purposeID="p3" variantID="v31 v32 v33 v34 v35" />
    </kb:alternatives>

    <kb:constituents>
      <!-- variant v11 is constituted by purpose p111 and purpose p112 -->
      <kb:constitutes variantID="v11" purposeID="p111 p112" />
      <!-- variant v23 is constituted by purpose p1 -->
      <kb:constitutes variantID="v23" purposeID="p1" />
      <!-- variant v22 is constituted by purpose p3 and purpose p1 -->
      <kb:constitutes variantID="v22" purposeID="p3 p1" />
    </kb:constituents>

    <!-- 
    The following Events and Rule are not very reasonable but show
    the Syntax of a Rule-Definition.
    Please note, that a Rule and all its Events must be attched to
    the same Variant and that the Start-Element of the corresponding
    Context-Paths always must be the ID of that Variant!
    -->
    <kb:events>
      <kb:event variantID="v11" id="e0001">
        <kb:label>Trigger Event 1</kb:label>
        <kb:contextPath pathIDs="v11 p111 v1111" />
      </kb:event>
      <kb:event variantID="v11" id="e0002">
        <kb:label>Premise Event 1</kb:label>
        <kb:contextPath pathIDs="v11 p112" />
      </kb:event>
      <kb:event variantID="v11" id="e0003">
        <kb:label>Conclusion Event 1</kb:label>
        <kb:contextPath pathIDs="v11 p112 v1121" />
      </kb:event>
    </kb:events>

    <kb:rules>
      <!--
      The following Rule says:
      1. If e0001 and e0002 are true then e0003 must be applied (Modus Ponens)
      2. If e0002 is true but e0003 is false then e0001 must be forbidden (Modus Tollens) 
      -->
      <kb:rule id="rule42" variantID="v11" triggerEventID="e0001" premiseEventID="e0002" conclusionEventID="e0003">
         <kb:label>An example of a Rule</kb:label>
      </kb:rule>
    </kb:rules>

  </kb:data>

</kb:knowledgebase>

=== dtag-dbu/psikeds/KnowledgeBase/src/main/resources/candidates/kb.xml
<?xml version="1.0" encoding="UTF-8"?>
<kb:knowledgebase xmlns="http://org.psikeds.knowledgebase"
  xmlns:kb="http://org.psikeds.knowledgebase"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://org.psikeds.knowledgebase kb.xsd">

  <kb:meta>
    <kb:created>2013-06-13T15:00:00</kb:created>
    <kb:lastmodified>2013-07-15T13:30:00</kb:lastmodified>
    <kb:creator>marco@juliano.de</kb:creator>
    <kb:description>A simple example knowledge base</kb:description>
    <kb:description>Status: Work in Progress</kb:description>
  </kb:meta>

  <kb:data>
    <kb:features>
      <kb:feature id="f0001">
        <kb:label>Example1</kb:label>
      </kb:feature>
      <kb:feature id="f0002">
        <kb:label>Dummy2</kb:label>
      </kb:feature>
    </kb:features>

    <kb:purposes>
      <kb:purpose id="p1">
        <kb:label>Sweets</kb:label>
      </kb:purpose>
      <kb:purpose id="p2">
        <kb:label>Packaging</kb:label>
      </kb:purpose>
      <kb:purpose id="p3">
        <kb:label>Drinking</kb:label>
      </kb:purpose>
    </kb:purposes>

    <kb:variants>
      <kb:variant id="v11">
        <kb:label>Milk Chocolate</kb:label>
      </kb:variant>
      <kb:variant id="v12">
        <kb:label>Diet Chocolate</kb:label>
      </kb:variant>
      <kb:variant id="v13">
        <kb:label>Gummy Bears</kb:label>
      </kb:variant>
      <kb:variant id="v14">
        <kb:label>Twix</kb:label>
      </kb:variant>
      <kb:variant id="v15">
        <kb:label>Duplo</kb:label>
      </kb:variant>
      <kb:variant id="v16">
        <kb:label>Licorice</kb:label>
      </kb:variant>
      <kb:variant id="v21">
        <kb:label>No Packaging</kb:label>
      </kb:variant>
      <kb:variant id="v22">
        <kb:label>Cardboard Box</kb:label>
      </kb:variant>
      <kb:variant id="v23">
        <kb:label>Aluminum Foil</kb:label>
      </kb:variant>
      <kb:variant id="v24">
        <kb:label>Bottle</kb:label>
      </kb:variant>
      <kb:variant id="v25">
        <kb:label>Can</kb:label>
      </kb:variant>
      <kb:variant id="v31">
        <kb:label>Coca Cola</kb:label>
      </kb:variant>
      <kb:variant id="v32">
        <kb:label>Pepsi Cola</kb:label>
      </kb:variant>
      <kb:variant id="v33">
        <kb:label>Budweiser</kb:label>
      </kb:variant>
      <kb:variant id="v34">
        <kb:label>Mineral Water</kb:label>
      </kb:variant>
      <kb:variant id="v35">
        <kb:label>Red Wine</kb:label>
      </kb:variant>
    </kb:variants>

    <kb:alternatives>
      <!-- purpose p1 is fulfilled by variant v11 or v12 or v13 or ... -->
      <kb:fulfills purposeID="p1" variantID="v11 v12 v13 v14 v15 v16" />
      <!-- purpose p2 is fulfilled by variant v21 or v22 or ... -->
      <kb:fulfills purposeID="p2" variantID="v21 v22 v23 v24 v25" />
      <!-- purpose p3 is fulfilled by variant v31 or v32 or ... -->
      <kb:fulfills purposeID="p3" variantID="v31 v32 v33 v34 v35" />
    </kb:alternatives>

    <kb:constituents>
      <!-- variant v11 is constituted by purpose p2 and purpose p3 -->
      <kb:constitutes variantID="v3333" purposeID="p2 p3" />
      <!-- variant v23 is constituted by purpose p1 -->
      <kb:constitutes variantID="v23" purposeID="p1" />
      <!-- variant v22 is constituted by purpose p3 and purpose p1 -->
      <kb:constitutes variantID="v22" purposeID="p3 p1" />
    </kb:constituents>

  </kb:data>

</kb:knowledgebase>

=== dtag-dbu/psikeds/KnowledgeBase/src/main/resources/candidates/ldrewe.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
ldrewe : 0.90 : demo database for the lecture on Linux Days 2014/Berlin 
(C) Karsten Reincke, Deutsche Telekom AG, Darmstadt 2014 

A psiKeds knowledge base: developed for being used by the inference machine
of psiKeds, the purpose system induced knowledge entity delivery system
http://www.psikeds.org/) and generated by the psiKedsXtXKrl-Generator

This file is licensed under the conditions of a/the
CC-BY-SA-4.0

-->
<kb:knowledgebase xmlns="http://org.psikeds.knowledgebase"
  xmlns:kb="http://org.psikeds.knowledgebase"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://org.psikeds.knowledgebase kb.xsd">
  
  <kb:meta>
    <kb:created>2014-05-05T14:00:00</kb:created>
    <kb:lastmodified>2014-05-06T10:52:37</kb:lastmodified>
    <kb:creator>Karsten Reincke</kb:creator>
    <kb:description>Linux-Day-Rewe-Demo-Knowledgebase</kb:description>
  </kb:meta>
  
  <kb:data>  

    <kb:purposes>
      <kb:purpose id="relishDinner" root="true">
        <kb:label>relish.Dinner</kb:label>
      </kb:purpose>
      <kb:purpose id="addTaste" root="false">
        <kb:label>add:Taste</kb:label>
      </kb:purpose>
      <kb:purpose id="addVitamins" root="false">
        <kb:label>add:Vitamins</kb:label>
      </kb:purpose>
      <kb:purpose id="addProteins" root="false">
        <kb:label>add:Proteins</kb:label>
      </kb:purpose>
      <kb:purpose id="addCarbohydrats" root="false">
        <kb:label>add:Carbohydrats</kb:label>
      </kb:purpose>
    </kb:purposes>

    <kb:variants>
      <kb:variant id="VeggiMeal">
        <kb:label>Veggi Meal</kb:label>
      </kb:variant>

      <kb:variant id="CarniMeal">
        <kb:label>Carni Meal</kb:label>
      </kb:variant>

      <kb:variant id="Hollandaise">
        <kb:label>Sauce Hollandaise</kb:label>
      </kb:variant>

      <kb:variant id="BratenSosse">
        <kb:label>Bratenso√üe</kb:label>
      </kb:variant>

      <kb:variant id="Spargel">
        <kb:label>Spargel</kb:label>
      </kb:variant>

      <kb:variant id="Erbsen">
        <kb:label>Erbsen</kb:label>
      </kb:variant>

      <kb:variant id="Schinken">
        <kb:label>Schinken</kb:label>
      </kb:variant>

      <kb:variant id="Braten">
        <kb:label>Braten</kb:label>
      </kb:variant>

      <kb:variant id="Kartoffeln">
        <kb:label>Kartoffeln</kb:label>
      </kb:variant>

      <kb:variant id="Nudeln">
        <kb:label>Nudeln</kb:label>
      </kb:variant>

    </kb:variants>  

    <kb:alternatives>
      <kb:fulfills purposeID="relishDinner" variantID="VeggiMeal CarniMeal" />
      <kb:fulfills purposeID="addTaste" variantID="Hollandaise BratenSosse" />
      <kb:fulfills purposeID="addVitamins" variantID="Spargel Erbsen" />
      <kb:fulfills purposeID="addProteins" variantID="Braten Schinken" />
      <kb:fulfills purposeID="addCarbohydrats" variantID="Kartoffeln Nudeln" />
    </kb:alternatives>  

    <kb:constituents>
      <kb:constitutes variantID="VeggiMeal" purposeID="addTaste addVitamins addCarbohydrats" />
      <kb:constitutes variantID="CarniMeal" purposeID="addTaste addVitamins addProteins addCarbohydrats" />
    </kb:constituents> 


    <kb:events>

      <kb:event id="VeggiMealWithTasteX" variantID="VeggiMeal">
        <kb:label>Veggi Meal mit TasteX</kb:label>
        <kb:contextPath pathIDs="VeggiMeal addTaste" /> 
      </kb:event>
      <kb:event id="VeggiMealWithHollandaise" variantID="VeggiMeal">
        <kb:label>Veggi Meal mit Hollandaise</kb:label>
        <kb:contextPath pathIDs="VeggiMeal addTaste Hollandaise" /> 
      </kb:event>

      <kb:event id="VeggiMealWithVitaminX" variantID="VeggiMeal">
        <kb:label>Veggi Meal mit VitaminX</kb:label>      
        <kb:contextPath pathIDs="VeggiMeal addVitamins" /> 
       </kb:event>
      <kb:event id="VeggiMealWithSpargel" variantID="VeggiMeal">
        <kb:label>Veggi Meal mit Spargel</kb:label>      
        <kb:contextPath pathIDs="VeggiMeal addVitamins Spargel" /> 
       </kb:event>      
 
       <kb:event id="CarniMealWithTasteX" variantID="CarniMeal">
        <kb:label>Carni Meal mit TasteX</kb:label>
        <kb:contextPath pathIDs="CarniMeal addTaste" /> 
      </kb:event>
      <kb:event id="CarniMealWithHollandaise" variantID="CarniMeal">
        <kb:label>Carni Meal mit Hollandaise</kb:label>
        <kb:contextPath pathIDs="CarniMeal addTaste Hollandaise" /> 
      </kb:event>
 
      <kb:event id="CarniMealWithVitaminX" variantID="CarniMeal">
        <kb:label>Carni Meal mit VitaminX</kb:label>
        <kb:contextPath pathIDs="CarniMeal addVitamins" /> 
      </kb:event>       
      <kb:event id="CarniMealWithSpargel" variantID="CarniMeal">
        <kb:label>Carni Meal mit Spargel</kb:label>
        <kb:contextPath pathIDs="CarniMeal addVitamins Spargel" /> 
      </kb:event>

       <kb:event id="CarniMealWithProteinX" variantID="CarniMeal">
        <kb:label>Carni Meal mit ProteinX</kb:label>
        <kb:contextPath pathIDs="CarniMeal addProteins" /> 
      </kb:event>      
      <kb:event id="CarniMealWithSchinken" variantID="CarniMeal">
        <kb:label>Carni Meal mit Schinken</kb:label>
        <kb:contextPath pathIDs="CarniMeal addProteins Schinken" /> 
      </kb:event>

      <kb:event id="CarniMealWithCarboX" variantID="CarniMeal">
        <kb:label>Carni Meal mit KohlehydratX</kb:label>
        <kb:contextPath pathIDs="CarniMeal addCarbohydrats" /> 
      </kb:event>      
      <kb:event id="CarniMealWithKartoffeln" variantID="CarniMeal">
        <kb:label>Carni Meal mit Kartoffeln</kb:label>
        <kb:contextPath pathIDs="CarniMeal addCarbohydrats Kartoffeln" /> 
      </kb:event>

      <kb:event id="VeggiMealWithCarboX" variantID="VeggiMeal">
        <kb:label>VeggiMeal mit KohlehydratX</kb:label>
        <kb:contextPath pathIDs="VeggiMeal addCarbohydrats" /> 
      </kb:event>
      
      <kb:event id="VeggiMealWithKartoffeln" variantID="VeggiMeal">
        <kb:label>VeggiMeal mit Kartoffeln</kb:label>
        <kb:contextPath pathIDs="VeggiMeal addCarbohydrats Kartoffeln" /> 
      </kb:event>
    </kb:events> 


    <kb:rules>

      <kb:rule 
        id="IFVMwithHoolandaiseTHENVMwithSpargel"
        variantID="VeggiMeal"
        triggerEventID="VeggiMealWithHollandaise"        
        premiseEventID="VeggiMealWithVitaminX"
        conclusionEventID="VeggiMealWithSpargel" >
        <kb:label>IF VM mit Hoolandaise THEN VM mit Spargel</kb:label>
      </kb:rule>

      <kb:rule 
        id="IFVMwithSpargelTHENVMwithHoolandaise"
        variantID="VeggiMeal"
        triggerEventID="VeggiMealWithSpargel"
        premiseEventID="VeggiMealWithTasteX"
        conclusionEventID="VeggiMealWithHollandaise" >
        <kb:label>IF VM mit Spargel THEN VM mit Hollandaise</kb:label>
      </kb:rule>

      <kb:rule 
        id="IFCMwithHoolandaiseTHENCMwithSpargel"
        variantID="CarniMeal"
        triggerEventID="CarniMealWithHollandaise"
        premiseEventID="CarniMealWithVitaminX"
        conclusionEventID="CarniMealWithSpargel" >
        <kb:label>IF CM mit Hoolandaise THEN CM mit Spargel</kb:label>
      </kb:rule>

      <kb:rule 
        id="IFCMwithSpargelTHENCMwithHoolandaise"
        variantID="CarniMeal"
        triggerEventID="CarniMealWithSpargel"
        premiseEventID="CarniMealWithTasteX"
        conclusionEventID="CarniMealWithHollandaise" >
        <kb:label>IF CM mit Spargel THEN CM mit Hollandaise</kb:label>
      </kb:rule>

      <kb:rule 
        id="IFCMwithSpargelTHENCMwithSchinken"
        variantID="CarniMeal"
        triggerEventID="CarniMealWithSpargel"
        premiseEventID="CarniMealWithProteinX"
        conclusionEventID="CarniMealWithSchinken" >
        <kb:label>IF CM mit Spargel THEN CM mit Schinken</kb:label>
      </kb:rule>

      <kb:rule 
        id="IFCMwithSpargelTHENCMwithKartoffeln"
        variantID="CarniMeal"
        triggerEventID="CarniMealWithSpargel"
        premiseEventID="CarniMealWithCarboX"
        conclusionEventID="CarniMealWithKartoffeln" >
        <kb:label>IF CM mit Spargel THEN CM mit Kartoffeln</kb:label>
      </kb:rule>

      <kb:rule 
        id="IFVMwithSpargelTHENVMwithKartoffeln"
        variantID="VeggiMeal"
        triggerEventID="VeggiMealWithSpargel"
        premiseEventID="VeggiMealWithCarboX"
        conclusionEventID="VeggiMealWithKartoffeln" >
        <kb:label>IF VM mit Spargel THEN VM mit Kartoffeln</kb:label>
      </kb:rule>
    </kb:rules> 

  </kb:data>    
</kb:knowledgebase>
